### ISSUE TITLE
bit_rate change is too big

### ISSUE THREAD

**Issue by BianGuangRong** [pkuvcl/buildFFmpegAVS2#1]
I use ffmpeg  transcode an video stream,  bit_rate is set to 9M.  During the transcoding, the bitrate variation range is too big, from 200kbps to 15Mbps. When 200kbps, the video picture is not distinct and lasts for a long period of time.
   input: Simpsons.mkv,  h264  1280x720,    23.98 fps,   2215 kb/s
   output:  udp                avs2    1920x1080,  23.98 fps,  10Mbps

**Comment by luofalei** [comment]
This is caused by `xavs2` encoder, The rate-control module of `xavs2` is not steady enough during parallel encoding, it should be improved in later development.
