### ISSUE TITLE
Dose FFmpegAVS2 support libxavs2?

### ISSUE THREAD

**Issue by yaowangvrviu** [pkuvcl/buildFFmpegAVS2#3]
In build_linux.sh file,
###############################
# build ffmpeg decoder
###############################
echo "$msg_color[Start building FFmpegAVS2]$reset_color"
cd FFmpegAVS2
git checkout avs2
export PKG_CONFIG_PATH=$build_dir/avs2_lib/lib/pkgconfig
printLog ./configure \
  --prefix=$build_dir/avs2_lib \
  --enable-gpl \
  --enable-libxavs2 \
  --enable-libdavs2 \          <=====================
  --enable-shared \
  --enable-static
------------------------------------------------
**Unknown option "--enable-libxavs2".**
See ./configure --help for available options.

Search in configure file there are
   --enable-libdavs2        enable AVS2 decoding via libdavs2 [no]
   --enable-libxavs          enable AVS encoding via xavs [no]
libxavs is libxavs2 ????

**Comment by luofalei** [comment]
`libxavs` is for `AVS1` and `libxavs2` is for `AVS2`.
They are not the same.
Is the `FFmpegAVS2` repository kept the same as the latest branch?

**Comment by yaowangvrviu** [comment]
我在FFmpegAVS2代码里面没看到有libxavs2.c这样的文件，在configure里面也没看到-enable libxavs2。我用的是最新的版本。

发自我的华为手机

-------- 原始邮件 --------
主题：Re: [pkuvcl/buildFFmpegAVS2] Dose FFmpegAVS2 support libxavs2? (#3)
发件人：Falei LUO
收件人：pkuvcl/buildFFmpegAVS2
抄送：Yao Wang ,Author


libxavs is for AVS1 and libxavs2 is for AVS2.
They are not the same.
Is the FFmpegAVS2 repository kept the same as the latest branch?

―

**Comment by luofalei** [comment]
The AVS2 sources are in the `avs2` branch of our `FFmpegAVS2` repository.
This was shown in the following command in `build_linux.sh` of current repository.
```
cd FFmpegAVS2
git checkout avs2
```

**Comment by yaowangvrviu** [comment]
ok. I see. Thank you very much. I will try.

发自我的华为手机

-------- 原始邮件 --------
主题：Re: [pkuvcl/buildFFmpegAVS2] Dose FFmpegAVS2 support libxavs2? (#3)
发件人：Falei LUO
收件人：pkuvcl/buildFFmpegAVS2
抄送：Yao Wang ,Author


The AVS2 sources are in the avs2 branch of our FFmpegAVS2 repository.
This was shown in the following command in build_linux.sh of current repository.

cd FFmpegAVS2
git checkout avs2


―
